apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-newapp
  labels:
    app: hello-newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-newapp
  template:
    metadata:
      labels:
        app: hello-newapp
    spec:
      containers:
        - name: hello-newapp
          image: vladxgx/hello-newapp:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
