apiVersion: v1
kind: Service
metadata:
  name: hello-newapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app: hello-newapp
  ports:
    - port: 8000
      targetPort: 8000
